spring:
  application:
    name: parking_system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parkingsystem
    username: postgres
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
  flyway:
    enabled: false
logging:
  level:
    org.springframework.security: DEBUG