spring:
  main:
    allow-circular-references: true
  application:
    name: parking_system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parkingsystem
    username: postgres
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  profiles:
    active: dev
  flyway:
    enabled: false

security:
  jwt:
    secret: parking-system-secret-key-felipe-schwartz-2026
    expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true